export class StyleUtil {

/**
 * Creates a <link> element in the head of the document to dynamically load a
 * style bundle at runtime.
 *
 * Angular.json allows to define style bundles that should be loaded dynamically
 * at runtime. These bundles will then be available in the build artifact but
 * you still must create a <link> for them in the document header. The link is
 * generated by this function.
 *
 * A dynamic bundle must be defined like this:
 *
 * ´´´´json
 * {
    "input": "./node_modules/leaflet/dist/leaflet.css", "bundleName": "leaflet",
    "inject": false
    },
 * ´´´´
 *
 * @param document
 * @param groupId - Used to create an ID for the link element: <link
 * id='goupId'>. Can be some random unique ID or a name identifying a group
 * whose styles might be interchangeable. For example, if you use dynamic styles
 * to switch styles of different tennants, then a group name for this use case
 * could be 'tennant'.
 * @param bundleName - The name of the CSS bundle to load as defined in
 * angular.json.
 */
  public static loadStyleBundle(
    document: Document,
    groupId: string,
    bundleName: string
  ): void {
    const head = document.getElementsByTagName('head')[0];

    const cssBundleLink = document.getElementById(groupId) as HTMLLinkElement;
    if (cssBundleLink) {
      cssBundleLink.href = bundleName;
    } else {
      const style = document.createElement('link');
      style.id = 'leaflet';
      style.rel = 'stylesheet';
      style.href = `${bundleName}`;

      head.appendChild(style);
    }
  }
}
