name: E2E Report
on:
  push:
    branches:
      - 'master'
      - 'feat-*'

env:
  # Extracting the branch name:
  # For GITHUB_REF=refs/heads/feature-branch-1
  # ${GITHUB_REF##*/} will be 'feature-branch-1'
  BRANCH: ${GITHUB_REF##*/}

jobs:
  cypress-run:
    name: E2E on Chrome v81
    runs-on: ubuntu-18.04
    # Cypress Docker image with Chrome v81
    # and Firefox pre-installed
    container: cypress/browsers:node14.16.0-chrome89-ff86

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
          npm ci
          $(npm bin)/cypress cache path
          $(npm bin)/cypress cache list
          $(npm bin)/cypress verify
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_PKG_TOKEN}}
      - name: Run tests
        run: npm run seed:e2e:report -- --config baseUrl=https://edible-garden.herokuapp.com/en --env locale=en
        continue-on-error: true
      - name: Copy test execution videos
        run: |
          mkdir public
          cp -r cypress/videos public/videos
      - name: Merge test execution results
        run: npm run e2e-report:merge
      - name: Generate report
        run: npm run e2e-report:generate
      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: seed-e2e-report
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
