# Deploy a branch of choice to QA environment
name: Manual deploy QA

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy to QA'
        default: "main"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      # akhileshns/heroku-deploy@v3.12.12
      - uses: akhileshns/heroku-deploy@79ef2ae4ff9b897010907016b268fd0f88561820
        with:
          branch: ${{ github.event.inputs.branch }}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.QA_HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          dontuseforce: false
          usedocker: true
          docker_heroku_process_type: web
          region: eu
          docker_build_args: |
            GH_PKG_TOKEN
            NG_BUILD_CONFIG
        env:
          NG_BUILD_CONFIG: qa
          GH_PKG_TOKEN: ${{secrets.GH_PKG_TOKEN}}
          NGINX_PROXY_PASS: ${{secrets.QA_NGINX_PROXY_PASS}}

